spring.application.name=Kosmo_api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.zvbgzlbhwjxrtmqdvrjw
spring.datasource.password=UQBv8xlW0QMdnxeN
